EcommerceWebsite/EcommerceWebsite/Controllers/NavController.cs
using EcommerceWebsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EcommerceWebsite.Controllers
{
    public class NavController : Controller
    {
        EcommerceEntities db = new EcommerceEntities();
        //
        // GET: /Nav/
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            var categoriesList = new List<CategoryViewModel>();
            foreach (var item in db.Categories)
            {
                if (item.ParentCategoryId == 0)
                {
                    var subCategories = db.Categories
                                                    .Where(x => x.ParentCategoryId == item.Id)
                                                    .Select(x => x.Name);
                    categoriesList.Add(new CategoryViewModel { Name = item.Name, SubCategory = subCategories.ToList() });
                }
            }            
            return PartialView(categoriesList);
        }

        public PartialViewResult TopMenu()
        {
            var categoriesList = new List<CategoryViewModel>();
            foreach (var item in db.Categories)
            {
                if (item.ParentCategoryId == 0)
                {
                    var subCategories = db.Categories
                                                    .Where(x => x.ParentCategoryId == item.Id)
                                                    .Select(x => x.Name);
                    categoriesList.Add(new CategoryViewModel { Name = item.Name, SubCategory = subCategories.ToList() });
                }
            }
            return PartialView(categoriesList);
        }
	}
}

EcommerceWebsite/EcommerceWebsite/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/CSS/Style.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.2.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="container" style="width:80%; margin-bottom:40px;">
        <div class="top-menu">
            <ul class="list-inline pull-right" style="padding:10px 0 0 10px;">
                @if (Request.IsAuthenticated)
                {
                    <li id="topitem">
                        <span class="glyphicon glyphicon-user"></span>
                        <strong>Hello, @Html.Encode(User.Identity.Name)</strong>
                    </li>
                    <li id="topitem">
                        <span class="glyphicon glyphicon-log-out"></span>
                        @Html.ActionLink("Log Out", "Logout", "Account")
                    </li>
                }
                else
                {
                    <li id="topitem">
                        <span class="glyphicon glyphicon-user"></span>
                        @Html.ActionLink("Sign Up", "Register", "Account")
                    </li>
                    <li id="topitem">
                        <span class="glyphicon glyphicon-log-in"></span>
                        @Html.ActionLink("Log in", "Login", "Account")
                    </li>
                }
                <li id="topitem">
                    <a href="/Cart/Index">
                        <span class="glyphicon glyphicon-shopping-cart"></span> Cart
                    </a>
                </li>
                @if (Request.IsAuthenticated)
                {
                    if (HttpContext.Current.User.IsInRole("Adminstrators"))
                    {
                        <li id="topitem">
                            <a href="~/Admin/AdminIndex">
                                <span class="glyphicon glyphicon-user"></span> Admin
                            </a>
                        </li>
                    }
                }
            </ul>
        </div>
        <br />  <hr />

        <div style="margin:20px 0 40px;">
            <h2 id="sitetitle">@Html.ActionLink("e-Commerce", "Home", "Home")</h2>
            <form class="form-inline pull-right" style="margin:10px 20px 0 0;" action="~/Product/Search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search" id="searchCriteria" name="searchCriteria">
                </div>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
            </form>
            <p id="titletag">Shop Online</p>
        </div> <hr />

        <div>
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success">@TempData["message"]</div>
            }
            @RenderBody()
        </div>
</body>
</html>

EcommerceWebsite/EcommerceWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/CSS/Style.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.2.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>

<body>
    <div class="container" style="width:80%; margin-bottom:40px;">
        <div class="top-menu">
            <ul class="list-inline pull-right" style="padding:10px 0 0 10px;">
                @if (Request.IsAuthenticated)
                {
                    <li id="topitem">
                        <span class="glyphicon glyphicon-user"></span>
                        <strong>Hello, @Html.Encode(User.Identity.Name)</strong>
                    </li>
                    <li id="topitem">
                        <span class="glyphicon glyphicon-log-out"></span>
                        @Html.ActionLink("Log Out", "Logout", "Account")
                    </li>
                }
                else
                {
                    <li id="topitem">
                        <span class="glyphicon glyphicon-user"></span>
                        @Html.ActionLink("Sign Up", "Register", "Account")
                    </li>
                    <li id="topitem">
                        <span class="glyphicon glyphicon-log-in"></span>
                        @Html.ActionLink("Log in", "Login", "Account")
                    </li>
                }

                @*<li id="topitem"><a href="~/Account/Register">
                    <span class="glyphicon glyphicon-user"></span> Sign Up</a>
                </li>
                <li id="topitem"><a href="~/Account/Login">
                    <span class="glyphicon glyphicon-log-in"></span> Log in</a>
                </li>*@
                <li id="topitem"><a href="~/Cart/Index">
                    <span class="glyphicon glyphicon-shopping-cart"></span> Cart</a>
                </li>

                @if (Request.IsAuthenticated)
                {
                    if (HttpContext.Current.User.IsInRole("Adminstrators"))
                    {
                        <li id="topitem">
                            <a href="~/Admin/AdminIndex">
                                <span class="glyphicon glyphicon-user"></span> Admin
                            </a>
                        </li>
                    }
                }
            </ul>
        </div>
        <br />  <hr />

        <div style="margin:20px 0 40px;">
            <h2 id="sitetitle">@Html.ActionLink("e-Commerce", "Home", "Home")</h2>
            <form class="form-inline pull-right" style="margin:10px 20px 0 0;" action="~/Product/Search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search" id="searchCriteria" name="searchCriteria">
                </div>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
            </form>
            <p id="titletag">Shop Online</p>
        </div> <hr />

        <nav class="navbar">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav" style="">
                        @Html.Action("TopMenu", "Nav")
                    </ul>
                </div>
            </div>
        </nav>
        <hr/>
    </div>

<div class="container">
    <div class="row">
        <div class="col-md-3 hidden-xs" style="width:20%;margin-left:25px;height:680px;margin-top:70px;">
            <p class="sidemenutitle"><strong>Categories</strong></p><hr />
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-md-9" style="width:68%; margin-left:60px;">
            @RenderBody()
        </div>
    </div>

    <div class="row" style="clear:both;text-align:center;margin-top:80px;"><hr />
        <p>&copy; @DateTime.Now.Year - e-commerce store</p>
    </div>
</div>

</body>
</html>

EcommerceWebsite/EcommerceWebsite/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/CSS/Style.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.2.0.min.js"></script>

    <script src="~/Scripts/bootstrap.min.js"></script>
</head>

<body>
    <div class="container" style="width:80%; margin-bottom:40px;">
        <div class="top-menu">
            <ul class="list-inline pull-right" style="padding:10px 0 0 10px;">
               @if (Request.IsAuthenticated)
                {
                    <li id="topitem">
                        <span class="glyphicon glyphicon-user"></span>
                        <strong>Hello, @Html.Encode(User.Identity.Name)</strong>
                    </li>
                    <li id="topitem">
                        <span class="glyphicon glyphicon-log-out"></span>
                        @Html.ActionLink("Log Out", "Logout", "Account")
                    </li>
                }
               else
               {
                    <li id="topitem">
                        <span class="glyphicon glyphicon-user"></span>
                        @Html.ActionLink("Sign Up", "Register", "Account")
                    </li>
                    <li id="topitem">
                        <span class="glyphicon glyphicon-log-in"></span>
                        @Html.ActionLink("Log in", "Login", "Account")
                    </li>
               }
                <li id="topitem"><a href="/Cart/Index">
                    <span class="glyphicon glyphicon-shopping-cart"></span> Cart </a>
                </li>
                @if (Request.IsAuthenticated) {
                    if (HttpContext.Current.User.IsInRole("Adminstrators")) { 
                <li   id="topitem"><a href="~/Admin/AdminIndex">
                        <span class="glyphicon glyphicon-user"></span> Admin</a>
                </li>
                }
                }
            </ul>
        </div>
        <br />  <hr />

        <div style="margin:20px 0 40px;">
            <h2 id="sitetitle">@Html.ActionLink("e-Commerce", "Home", "Home")</h2>
            <form class="form-inline pull-right" style="margin:10px 20px 0 0;" action="~/Product/Search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search" id="searchCriteria" name="searchCriteria">
                </div>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
            </form>
            <p id="titletag">Shop Online</p>
        </div> <hr />

        <nav class="navbar hidden-xs">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav" style="">
                        @Html.Action("TopMenu", "Nav")
                    </ul>
                </div>
            </div>
        </nav>
        <hr />
    </div>

    <div class="container">
        @RenderBody()
        <div class="row" style="clear:both;text-align:center;margin-top:80px;"><hr/>
            <p>&copy; @DateTime.Now.Year - e-commerce store</p>
        </div>
    </div>

</body>
</html>