EcommerceWebsite/EcommerceWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace EcommerceWebsite.Controllers
{
    public class HomeController : Controller
    {
        EcommerceEntities db = new EcommerceEntities();
        //
        // GET: /Home/
        /*public ActionResult Index()
        {
            EcommerceEntities db = new EcommerceEntities();
            IEnumerable<Product> products = db.Products;
            return View(products);
        }*/

        public ActionResult Home()
        {
            return View();
        }


        public ActionResult Index(string category)
        {            
            var products = (from p in db.Products.Include("Product_Category_Mapping")
                            where p.Product_Category_Mapping.Any(c => category == null || c.Category.Name == category)
                            select p).ToList();
                                         
            return View(products);
        }
	}
}

EcommerceWebsite/EcommerceWebsite/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace EcommerceWebsite.Controllers
{
    public class ImageController : Controller
    {
        EcommerceEntities db = new EcommerceEntities();
        //
        // GET: /Image/
        public ActionResult show(int id)
        {            
            var picture = db.Product_Picture_Mapping.Include(x => x.Picture)
                                    .Where(x => x.ProductId == id)
                                    .FirstOrDefault();
            return File(picture.Picture.PictureBinary, picture.Picture.MimeType);
        }
	}
}

EcommerceWebsite/EcommerceWebsite/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace EcommerceWebsite.Controllers
{
    public class ProductController : Controller
    {
        EcommerceEntities db = new EcommerceEntities();
        //
        // GET: /Product/
        public ActionResult MainProducts(string category, string searchCriteria)
        {
            var _category = db.Categories.Where(x => x.Name == category).FirstOrDefault();

            var products = (from p in db.Products.Include("Product_Category_Mapping")
                                        where p.Product_Category_Mapping
                                                    .Any(c => category == null || 
                                                            c.Category.Name == category || 
                                                            c.Category.ParentCategoryId == _category.Id)
                                        select p).ToList();

            return View("List", products);
            //return View(products);
            //return View("MainProducts", "~/Views/Shared/_MenuLayout.cshtml", products);
        }

        public ActionResult Search(string searchCriteria)
        {
            var products = (from p in db.Products
                            where (p.Name.Contains(searchCriteria) ||  p.FullDescription.Contains(searchCriteria))
                            select p).ToList();

            return View("List", products);
        }

        public ActionResult SubcategoryProducts(string category)
        {
            var products = (from p in db.Products.Include("Product_Category_Mapping")
                            where p.Product_Category_Mapping
                                        .Any(c => category == null || c.Category.Name == category)
                            select p).ToList();

            return View("List", products);
            //return View(products);
            //return View("SubcategoryProducts", "~/Views/Shared/_MenuLayout.cshtml", products);
        }

        public ActionResult Detail(int id) {
            var product = db.Products.Where(p => p.Id == id).FirstOrDefault();
            return View(product);            
            //return View("Detail", "~/Views/Shared/_Layout.cshtml", product);
        }
	}
}

EcommerceWebsite/EcommerceWebsite/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="container" style="width:90%;">
    <div class="row" style="margin-top:-15px;">
        <a href='@Url.Action("MainProducts", "Product", new { category = "Computers" })'>
            <p id="homeCategTitle">Computers</p><hr />
        </a>
            <div class="col-md-4">
                <h4 id="homeImgtitle">Desktops</h4>
                <a href='@Url.Action("SubcategoryProducts", "Product", new { category = "Desktops" })'>
                    <img src="~/Content/Images/Desktop.jpg" id="homepImg" />
                </a>
            </div>

            <div class="col-md-4">
                <h4 id="homeImgtitle">Notebooks</h4>
                <a href='@Url.Action("SubcategoryProducts", "Product", new { category = "Notebooks" })'>
                    <img src="~/Content/Images/Notebook.jpg" id="homepImg" />
                </a>
            </div>

            <div class="col-md-4">
                <h4 id="homeImgtitle">Software</h4>
                <a href='@Url.Action("SubcategoryProducts", "Product", new { category = "Software" })'>
                    <img src="~/Content/Images/Software.jpg" id="homepImg" />
                </a>
            </div>
    </div>

    <div class="row" style="margin-top:50px;">
        <a href='@Url.Action("MainProducts", "Product", new { category = "Electronics" })'>
            <p id="homeCategTitle">Electronics</p><hr />
        </a>
        <div class="col-md-4">
            <h4 id="homeImgtitle">Camera & photo</h4>
            <a href='@Url.Action("SubcategoryProducts", "Product", new { category = "Camera & photo" })'>
                <img src="~/Content/Images/Camera.jpeg" id="homepImg" />
            </a>
        </div>

        <div class="col-md-4">
            <h4 id="homeImgtitle">Cell phones</h4>
            <a href='@Url.Action("SubcategoryProducts", "Product", new { category = "Cell phones" })'>
                <img src="~/Content/Images/CellPhone.jpeg" id="homepImg" />
            </a>
        </div>

        <div class="col-md-4">
            <h4 id="homeImgtitle">Others</h4>
            <a href='@Url.Action("SubcategoryProducts", "Product", new { category = "Others" })'>
                <img src="~/Content/Images/Others.jpg" id="homepImg" />
            </a>
        </div>
    </div>

    <div class="row" style="margin-top:50px;">
        <a href='@Url.Action("MainProducts", "Product", new { category = "Apparel" })'>
            <p id="homeCategTitle">Apparel</p><hr />
        </a>
        <div class="col-md-4">
            <h4 id="homeImgtitle">Shoes</h4>
            <a href='@Url.Action("SubcategoryProducts", "Product", new { category = "Shoes" })'>
                <img src="~/Content/Images/Shoes.jpg" id="homepImg" />
            </a>
        </div>

        <div class="col-md-4">
            <h4 id="homeImgtitle">Clothing</h4>
            <a href='@Url.Action("SubcategoryProducts", "Product", new { category = "Clothing" })'>
                <img src="~/Content/Images/Clothing.jpg" id="homepImg" />
            </a>
        </div>

        <div class="col-md-4">
            <h4 id="homeImgtitle">Accessories</h4>
            <a href='@Url.Action("SubcategoryProducts", "Product", new { category = "Accessories" })'>
                <img src="~/Content/Images/Accessories.jpg" id="homepImg" />
            </a>
        </div>
    </div>

    <div class="row" style="margin-top:50px;">
        <a href='@Url.Action("MainProducts", "Product", new { category = "Digital downloads" })'>
            <p id="homeCategTitle">Digital downloads</p><hr />
        </a>
        <div class="col-md-4">
            <h4 id="homeImgtitle">Downloads</h4>
            <a href='@Url.Action("MainProducts", "Product", new { category = "Digital downloads" })'>
                <img src="~/Content/Images/Digital.jpg" id="homepImg" />
            </a>
        </div>
    </div>

    <div class="row" style="margin-top:50px;">
        <a href='@Url.Action("MainProducts", "Product", new { category = "Books" })'>
            <p id="homeCategTitle">Books</p><hr />
        </a>
        <div class="col-md-4">
            <h4 id="homeImgtitle">Books</h4>
            <a href='@Url.Action("MainProducts", "Product", new { category = "Books" })'>
                <img src="~/Content/Images/Books.png" id="homepImg" />
            </a>
        </div>
    </div>

    <div class="row" style="margin-top:50px;">
        <a href='@Url.Action("MainProducts", "Product", new { category = "Jewelry" })'>
            <p id="homeCategTitle">Jewelry</p><hr />
        </a>
        <div class="col-md-4">
            <h4 id="homeImgtitle">Jewelry</h4>
            <a href='@Url.Action("MainProducts", "Product", new { category = "Jewelry" })'>
                <img src="~/Content/Images/Jewelry.jpg" id="homepImg" />
            </a>
        </div>
    </div>

    <div class="row" style="margin-top:50px;">
        <a href='@Url.Action("MainProducts", "Product", new { category = "Gift Cards" })'>
            <p id="homeCategTitle">Gift Cards</p><hr />
        </a>
        <div class="col-md-4">
            <h4 id="homeImgtitle">Gift Cards</h4>
            <a href='@Url.Action("MainProducts", "Product", new { category = "Gift Cards" })'>
                <img src="~/Content/Images/GiftCard.jpg" id="homepImg" />
            </a>
        </div>
    </div>

</div>

EcommerceWebsite/EcommerceWebsite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@model IEnumerable<Product>

<div style="padding-top:40px;margin-left:-20px;" class="container-fluid">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-4">
                <div class="thumbnail right-caption span4" style="width: 250px; height: 400px;border:none;">
                    <img src='@Url.Action("show", "image", new { id = item.Id })' width="250" height="400" />
                    <div class="caption">
                        <h3>@item.Name</h3>
                        <div class="price">
                            <label class="btn btn-primary btn-sm">@item.Price.ToString("c")</label>
                        </div>
                        @*<p class="prdtdesc"> @item.ShortDescription</p>*@
                        @*@using (Html.BeginForm("AddToCart", "Cart"))
                            {
                                <div>
                                    @Html.HiddenFor(x => x.Id)
                                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                                    <input type="submit" class="btn btn-success" value="Add to cart" />
                                </div>
                            }*@
                    </div>
                </div>
            </div>
        }
    </div>
</div>


@*
    <div style="padding-top:50px;"class="container-fluid">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="products" style="overflow:hidden;">
                        <div class="picture">
                                <img src="@Url.Action("show", "Image", new { id = item.Id})" class="img-responsive" />
                            </div>
                        <div>
                            <h3 class="product-title">@item.Name</h3>
                            <div class=" prices">
                                <span class="label label-info">@item.Price.ToString("c")</span>
                            </div>
                            <span>@item.ShortDescription</span>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
*@